// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TESTEMINHAAPI.BancoDeDados;

#nullable disable

namespace TESTEMINHAAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623173913_licecesToken")]
    partial class licecesToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TESTEMINHAAPI.Models.Alternativas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("correta")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("criado")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ordem")
                        .HasColumnType("int");

                    b.Property<int>("questao_id")
                        .HasColumnType("int");

                    b.Property<int>("questaoid")
                        .HasColumnType("int");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("id");

                    b.HasIndex("questaoid");

                    b.ToTable("Alternativas");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Aulas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("criado")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("modulo_id")
                        .HasColumnType("int");

                    b.Property<int>("moduloid")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)");

                    b.HasKey("id");

                    b.HasIndex("moduloid");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Candidaturas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("curriculo_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.Property<int>("vaga_id")
                        .HasColumnType("int");

                    b.Property<int>("vagaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.HasIndex("vagaid");

                    b.ToTable("Candidaturas");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Certificados", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("emitido_em")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("treinamento_id")
                        .HasColumnType("int");

                    b.Property<int>("treinamentoid")
                        .HasColumnType("int");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("treinamentoid");

                    b.HasIndex("usuarioid");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Licencas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("criado_em")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.Property<DateTime>("validade_em")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("Licencas");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Midias", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("aula_id")
                        .HasColumnType("int");

                    b.Property<int>("aulaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("criado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("id");

                    b.HasIndex("aulaid");

                    b.ToTable("Midias");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Modulos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)");

                    b.Property<int>("treinamento_id")
                        .HasColumnType("int");

                    b.Property<int>("treinamentoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("treinamentoid");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Notas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("prova_id")
                        .HasColumnType("int");

                    b.Property<int?>("treinamento_id")
                        .HasColumnType("int");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Noticia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("data_noticia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("vaga")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Progress", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("atualizado_em")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("aula_id")
                        .HasColumnType("int");

                    b.Property<int>("aulaid")
                        .HasColumnType("int");

                    b.Property<decimal>("percentual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("tempo_segundos")
                        .HasColumnType("int");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("aulaid");

                    b.HasIndex("usuarioid");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Questoes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("aula_id")
                        .HasColumnType("int");

                    b.Property<int>("aulaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("criado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("id");

                    b.HasIndex("aulaid");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Reports", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Treinamentos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)");

                    b.HasKey("id");

                    b.ToTable("Treinamentos");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.UseProva", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("nota")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("prova_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("realizado_em")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("UseProva");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.UseTreinamentos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("matriculado_em")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("treinamento_id")
                        .HasColumnType("int");

                    b.Property<int>("treinamentoid")
                        .HasColumnType("int");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("treinamentoid");

                    b.HasIndex("usuarioid");

                    b.ToTable("UseTreinamentos");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("acesso")
                        .HasColumnType("int");

                    b.Property<int>("ativo")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("tipo")
                        .HasColumnType("int");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Vagas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("criado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("localizacao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("UsuarioTreinamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("treinamento_id")
                        .HasColumnType("int");

                    b.Property<int>("treinamentoid")
                        .HasColumnType("int");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("treinamentoid");

                    b.HasIndex("usuarioid");

                    b.ToTable("UsuarioTreinamentos");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Alternativas", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Questoes", "questao")
                        .WithMany("alternativas")
                        .HasForeignKey("questaoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("questao");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Aulas", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Modulos", "modulo")
                        .WithMany()
                        .HasForeignKey("moduloid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("modulo");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Candidaturas", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TESTEMINHAAPI.Models.Vagas", "vaga")
                        .WithMany()
                        .HasForeignKey("vagaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");

                    b.Navigation("vaga");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Certificados", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Treinamentos", "treinamento")
                        .WithMany()
                        .HasForeignKey("treinamentoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TESTEMINHAAPI.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("treinamento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Licencas", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Usuario", "usuario")
                        .WithMany("licencas")
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Midias", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Aulas", "aula")
                        .WithMany()
                        .HasForeignKey("aulaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aula");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Modulos", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Treinamentos", "treinamento")
                        .WithMany()
                        .HasForeignKey("treinamentoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("treinamento");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Notas", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Progress", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Aulas", "aula")
                        .WithMany()
                        .HasForeignKey("aulaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TESTEMINHAAPI.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aula");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Questoes", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Aulas", "aula")
                        .WithMany()
                        .HasForeignKey("aulaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aula");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Reports", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.UseProva", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.UseTreinamentos", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Treinamentos", "treinamento")
                        .WithMany()
                        .HasForeignKey("treinamentoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TESTEMINHAAPI.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("treinamento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("UsuarioTreinamento", b =>
                {
                    b.HasOne("TESTEMINHAAPI.Models.Treinamentos", "treinamento")
                        .WithMany()
                        .HasForeignKey("treinamentoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TESTEMINHAAPI.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("treinamento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Questoes", b =>
                {
                    b.Navigation("alternativas");
                });

            modelBuilder.Entity("TESTEMINHAAPI.Models.Usuario", b =>
                {
                    b.Navigation("licencas");
                });
#pragma warning restore 612, 618
        }
    }
}
